### ISSUE TITLE
Possibly unsound unchecked casts

### ISSUE THREAD

**Issue by nicolasstucki** [rssh/dotty-cps-async#15]
There are a couple of casts on `Expr` that seem to be unsound. To check those casts use the `cast` method.

```diff
- term.seal.asInstanceOf[Expr[T]]
+ term.seal.cast[T]
```
* https://github.com/rssh/dotty-cps-async/blob/master/src/main/scala/cps/forest/application/ApplyArgRecordScope.scala#L199-L200
* https://github.com/rssh/dotty-cps-async/blob/master/src/main/scala/cps/forest/ValDefTransform.scala#L142

Discovered in https://github.com/lampepfl/dotty/pull/9497

**Comment by rssh** [comment]
Thanks
 will switch now.

**Comment by rssh** [comment]
Converted all, except three entries, which,  I guess, show dotty bugs in type comparison.
[will submit separate bug-reports to dotty during the next possible timeslot.  For now - those cast-s commented out. ]

**Comment by nicolasstucki** [comment]
I just saw some other `.asInstanceOf[Expr[T]]` that are not after a `seal`, those should also use `cast[T]`
