### ISSUE TITLE
Async transformation does not support base effect capture

### ISSUE THREAD

**Issue by djspiewak** [rssh/dotty-cps-async#40]
Simple example:

```scala
async[IO](throw new Throwable)
```

This results in *eagerly* throwing an exception, rather than suspending that exception within `IO`. Similarly:

```scala
val _ = async[IO](println("test"))
```

This will print. I'm relatively certain that the `CpsMonad` abstraction is not quite powerful enough to handle this scenario. You almost certainly need to add something like `defer[A](thunk: => F[A]): F[A]`

**Comment by rssh** [comment]
Yes, introduced CpsDelayMonad[F]. with delayUnit() method.   
```async[F]{ x }```  is interpreted  as  
```F.delayUnit.flatMap(_ =>  cpsTransform(f)  )```

**Comment by djspiewak** [comment]
I think that only solves the immediate laziness problem. You're basically relying on `flatMap` for capture, which in turn is relying on properties that are not guaranteed by the underlying system (e.g. it isn't *guaranteed* that it will be run only once!). A better approach would be to have something like `defer`, which is a bit like a lazy `flatten`, and wrap *that* around `cpsTransform(f)`.

**Comment by rssh** [comment]
Hmm,  i.e.  can exists such `F[_]` that  `F.delay(())*flatMap(_ => a)  != F.delay(a)` ? 
I have thought that this is a left identity axiom.  Will recheck.

**Comment by djspiewak** [comment]
Couple things here. First, `delay` and `pure` aren't the same thing. The left identity law only applies to `pure`. So in a sense, we can't really say anything about this kind of equivalence, one way or another.

Even beyond that, the body of a `delay` is not referentially transparent. Clearly, `F.delay(println("sup?")) != F.delay(())`, and so even if we were in the business of rewriting the axioms, there's no way we can apply the conventional tools of substitutability to anything that is within those brackets.

Now, as a *practical* matter, many effect types will coincidentally define `F.delay(()).flatMap(_ => F.pure(a))` to equal `F.delay(a)`, but it's not really something that should be relied upon, particularly since there could exist subtle differences between the two.

**Comment by rssh** [comment]
I have thought about math expressions about effects, not about scala expressions about values.  It looks like the relation of the math formula vs. the scala expression is not apparent.

   Historically, the "effect" as a synonym of  "computation as value"  in Haskell uses lazy evaluation semantics.  Scalaz port also uses lazy evaluation in Applicative and, therefore, in Monad.   Cats changed Applicative to be eager, and thus, this design decision screwed Haskell’s intuition reasoning.  Law with cats 'pure' now becomes a projection of original, more deep law ( with Haskell 'return' = scalaz 'point'  = cats-effect 'delay').  But if we name a monad as an effect monad, it means that this references the original Haskell semantics?  (i.e. laws should be applied to delay).  So, I guess it will be hard to find an effect monad which not follow the 'á-la Hask' equations.
 
    Anyway, I added the possibility to override `delay` and `flatDelay` if you want this for whatever reason.
