### ISSUE TITLE
async does not do anything before first await

### ISSUE THREAD

**Issue by ScoreUnder** [rssh/dotty-cps-async#45]
I ported a project from Scala 2 to Scala 3 recently and switched from `scala-async` to `dotty-cps-async`, but after tracking down a strange issue in my program I have found that unlike in `scala-async`, the position of the beginning of the `async` block is always ignored.

If I have a program like this:

```scala
async {
  foo()
  await(bar())
}
```

Then that is the same as if it had been written:

```scala
foo()
bar()
```

This in practice means that if either of those functions perform heavy calculations, it will take place on the main thread. Exceptions will also be thrown on the main thread instead of contained inside the Future (like in #40). One way to get around this is to use `await(Future.unit)` at the start of every async block, but apparently marking FutureAsyncMonad with CpsEffectMonad also works to fix this.

However, it would be nice to have this in the code itself: overriding `FutureAsyncMonad` isn't possible because it is an anonymous class, so the whole class must be copy-pasted to extend it with this feature, but I believe that this is a reasonable thing to expect from `async[Future]` so should probably be included in the library.

**Comment by rssh** [comment]
To clarify:  compatibility issue,  FutureAsyncMonad starts evaluation in the main thread instead of spawning new.

**Comment by rssh** [comment]
0.9.1  will be with this fix shortly.

**Comment by rssh** [comment]
0.9.1 with fix is published
