### ISSUE TITLE
[Implement CpsMonad for scala.concurrent.Future]  (was: Even a nice example just showing its use to some remote APIs would be nice!)

### ISSUE THREAD

**Issue by rssh** [rssh/dotty-cps-async#8]
Even a nice example just showing its use to some remote APIs would be nice!

_Originally posted by @aappddeevv in https://github.com/rssh/dotty-cps-async/issues/6#issuecomment-613636233_

(Good  start will be implements mechanics for standard Future, and later - integration project with well-known effects libraries [cats-effects/monix/zio], when they will become available for dotty)

**Comment by aappddeevv** [comment]
Thanks! I'll give this a shot!
